language: python

stages:
  - lint
  - test
  - release

python:
  - "3.6"

before_install:
  - pip install poetry

install:
  - poetry install -v

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: test
      script:
        - make test
        - poetry run codecov
    - stage: release
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
      if: tag IS present

