language: python

services:
  - redis-server

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      before_install:
        - pip install poetry
      install:
        - poetry install -v
      script:
        - poetry run pylint audio_slackbot
        - poetry run black --check .
    - stage: test
      python:
        - "3.6"
        - "3.7"
      before_install:
        - pip install poetry
      install:
        - poetry install -v
      script:
        - poetry run pytest --cov=audio_slackbot --cov-report term-missing test/
        - poetry run codecov
